#!/bin/bash
#include <stdio.h>

/**

 * main - Entry point

 *

 * Return: Always 0 (Success)

 */

int main(void)

{
    return (0);

}
# 2 "main.c" 2

# 3 "main.c"

int main(void)

{

 return (0);

}
